name: Docker Image CI

on:
  push:
#   tags:
 #   - 'v*'
  # paths:
   #    - "app.js"
    #   - "package.json"
     #  - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build --no-cache \
          -t sanojkv/nginx-helm:latest \
          -t sanojkv/nginx-helm:${{ github.sha }} .
        docker push sanojkv/nginx-helm:latest
        docker push sanojkv/nginx-helm:${{ github.sha }}
    - name: Clone CD Repository
      run: |
       git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.CD_REPO_TOKEN }}@github.com/KvSanojKV/nginx-helm-CD.git
    - name: Update Image Tag
      run: |
        sed -i 's/tag:.*/tag: "${{ github.sha }}"/' nginx-helm-CD/helm/values.yaml
    - name: Update Image Tag
      run: |
       sed -i 's/tag:.*/tag: "${{ github.sha }}"/' nginx-helm-CD/helm/values.yaml
    - name: Commit Changes
      run: |
       cd nginx-helm-CD

       git config user.name "github-actions"
       git config user.email "github-actions@github.com"

       git add .

       git commit -m "Update image to ${{ github.sha }}"

    - name: Push Changes
      run: |
       cd nginx-helm-CD
       git push
